[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.20"
memory_limit = 43554432
gas_limit = 9223372036854775807
gas_price = 0
# optimizer
optimizer = true
# optimizer runs
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/tree/master/config